version: '3'
 
services:
  db:
    image: postgres:15.1
    restart: on-failure
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}      
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    container_name: login-unity
    volumes:
      - ./postgres_data:/var/lib/postgresql